# Generated by Django 2.0.1 on 2018-01-28 19:30

from django.db import migrations


def add_initial_data(apps, schema_editor):
    Category = apps.get_model('hr', 'Category')
    Subcategory = apps.get_model('hr', 'Subcategory')

    Automobile = Category.objects.create(name='Automobile')
    Subcategory.objects.create(name='Replacement-Parts', category=Automobile)
    Subcategory.objects.create(name='Oil-Fluids', category=Automobile)
    Subcategory.objects.create(name='Tyre-Rim', category=Automobile)
    Subcategory.objects.create(name='Interior Accessories', category=Automobile)
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
