# Generated by Django 2.0.1 on 2019-10-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_add_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='Designatedid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='comission',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
