# Generated by Django 2.0.1 on 2019-10-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20191004_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
