# Generated by Django 2.2.5 on 2019-10-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadedfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='file2',
            field=models.FileField(null=True, upload_to='CSVFiles'),
        ),
    ]
