# Generated by Django 2.2.5 on 2019-10-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_uploadedfiles_file2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfiles',
            name='file_name',
        ),
    ]
